### ISSUE TITLE
[SUGGESTION] Pillow is required to run but isn't used.

### ISSUE THREAD

**Issue by ghost** [Rudra1738/MapleCoinMiningSoftware#1]
Could you remove line 3 `from PIL import ImageTk, Image` from the MapleTk.py file? It seems it isn't used anywhere in the file as it runs perfectly fine without it and it isn't present in the code either. This'll help remove the need to install Pillow, not sure if anyone else's facing this issue though.

I apologize if this isn't the proper way to report issues or suggestions, I'm quite new to GitHub.

**Comment by Rudra1738** [comment]
It’s been fixed now, thanks for letting me know!
